// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----------- //
// pps_capture //
// ----------- //

#define pps_capture_wrap_target 0
#define pps_capture_wrap 3
#define pps_capture_pio_version 0

static const uint16_t pps_capture_program_instructions[] = {
            //     .wrap_target
    0x2020, //  0: wait   0 pin, 0
    0x20a0, //  1: wait   1 pin, 0
    0x4060, //  2: in     null, 32
    0x8000, //  3: push   noblock
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program pps_capture_program = {
    .instructions = pps_capture_program_instructions,
    .length = 4,
    .origin = -1,
    .pio_version = pps_capture_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config pps_capture_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + pps_capture_wrap_target, offset + pps_capture_wrap);
    return c;
}
#endif

// ----------------- //
// pps_capture_hires //
// ----------------- //

#define pps_capture_hires_wrap_target 1
#define pps_capture_hires_wrap 8
#define pps_capture_hires_pio_version 0

static const uint16_t pps_capture_hires_program_instructions[] = {
    0xe020, //  0: set    x, 0
            //     .wrap_target
    0x0042, //  1: jmp    x--, 2
    0x00c1, //  2: jmp    pin, 1
    0x0044, //  3: jmp    x--, 4
    0x00c6, //  4: jmp    pin, 6
    0x0003, //  5: jmp    3
    0x4020, //  6: in     x, 32
    0x8000, //  7: push   noblock
    0xe020, //  8: set    x, 0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program pps_capture_hires_program = {
    .instructions = pps_capture_hires_program_instructions,
    .length = 9,
    .origin = -1,
    .pio_version = pps_capture_hires_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config pps_capture_hires_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + pps_capture_hires_wrap_target, offset + pps_capture_hires_wrap);
    return c;
}
#endif

// ------------ //
// freq_counter //
// ------------ //

#define freq_counter_wrap_target 1
#define freq_counter_wrap 11
#define freq_counter_pio_version 0

static const uint16_t freq_counter_program_instructions[] = {
    0xe049, //  0: set    y, 9
            //     .wrap_target
    0x2021, //  1: wait   0 pin, 1
    0x20a1, //  2: wait   1 pin, 1
    0xa02b, //  3: mov    x, ~null
    0x0086, //  4: jmp    y--, 6
    0x0009, //  5: jmp    9
    0x2021, //  6: wait   0 pin, 1
    0x20a1, //  7: wait   1 pin, 1
    0x0044, //  8: jmp    x--, 4
    0x4020, //  9: in     x, 32
    0x8000, // 10: push   noblock
    0xe049, // 11: set    y, 9
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program freq_counter_program = {
    .instructions = freq_counter_program_instructions,
    .length = 12,
    .origin = -1,
    .pio_version = freq_counter_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config freq_counter_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + freq_counter_wrap_target, offset + freq_counter_wrap);
    return c;
}
#endif

