
[env:pico2]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2
framework = arduino
board_build.core = earlephilhower
lib_deps =
    Wire
    bblanchon/ArduinoJson @ ^6.20.0
monitor_speed = 115200
upload_protocol = picotool

; 150MHz = fully validated by Raspberry Pi, no overclocking
; Resolution = 6.67ns per PIO tick - adequate for GPS 1PPS work
; (GPS 1PPS accuracy ~20ns RMS dominates anyway)
board_build.f_cpu = 150000000L


; Optional/redundant: the chosen core already defines ARDUINO_ARCH_RP2040
; Uncomment if you explicitly want to define it again
;build_flags =
;    -D ARDUINO_ARCH_RP2040

[env:gpio_test]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2
framework = arduino
board_build.core = earlephilhower
monitor_speed = 115200
upload_protocol = picotool
board_build.f_cpu = 150000000L
build_src_filter = -<*> +<../test_gpio/pps_freq_counter_test.cpp>
